<template>
  <section class="bid-items-panel">
    <header class="bip-head">
      <h3>
        <Icon icon="mdi:format-list-bulleted" class="w-4 h-4" />
        {{ $t('Items') || 'Items' }}
        <span class="bip-count">{{ items.length }}</span>
      </h3>
      <button v-if="canEdit" class="btn-primary btn-sm" @click="openAddModal">
        <Icon icon="mdi:plus" class="w-4 h-4" />
        {{ $t('AddItem') || 'Add Item' }}
      </button>
    </header>

    <div v-if="items.length === 0" class="bip-empty">
      <Icon icon="mdi:format-list-bulleted" class="w-8 h-8" />
      <p>{{ $t('NoBidItems') || 'No items yet. Add one to start the visions cycle.' }}</p>
    </div>

    <div v-else class="bip-list">
      <article v-for="item in sortedItems" :key="item.id" class="bip-item">
        <div class="bip-item-head">
          <span class="bip-ref"><Icon icon="mdi:pound" class="w-3 h-3" />{{ item.referenceNumber }}</span>
          <span v-if="item.externalReferenceNumber" class="bip-ref-ext">{{ item.externalReferenceNumber }}</span>
          <span class="bip-order">#{{ item.order }}</span>
          <div v-if="canEdit" class="bip-item-actions">
            <button class="icon-btn" @click="openEditModal(item)" :title="$t('Edit')"><Icon icon="mdi:pencil-outline" class="w-4 h-4" /></button>
            <button class="icon-btn icon-btn-danger" @click="confirmDelete(item)" :title="$t('Delete')"><Icon icon="mdi:delete-outline" class="w-4 h-4" /></button>
          </div>
        </div>
        <div class="bip-content" v-html="item.content"></div>
        <div class="bip-item-meta">
          <span v-if="item.dueDate" class="bip-due" :class="{ overdue: isOverdue(item.dueDate) }">
            <Icon icon="mdi:calendar-clock" class="w-3 h-3" />
            {{ formatDate(item.dueDate) }}
            <em v-if="isOverdue(item.dueDate)" class="bip-overdue">{{ $t('Overdue') || 'Overdue' }}</em>
          </span>
          <span v-if="item.internalNote" class="bip-note">
            <Icon icon="mdi:note-outline" class="w-3 h-3" />
            {{ item.internalNote }}
          </span>
        </div>
      </article>
    </div>

    <!-- Add/Edit Modal -->
    <!-- Item modal needs room for: rich text editor, two type dropdowns, related-item picker,
         tags multi-select, dates, internal notes — `xl` (1000px) gives the editor and pickers
         enough horizontal space to feel comfortable rather than cramped. -->
    <ConfirmModal
      v-model="confirmOpen"
      :title="$t('ConfirmDeleteItem') || 'Delete item?'"
      :message="$t('ConfirmDeleteItemBody') || 'This will permanently remove the item from the bid. Continue?'"
      :confirm-text="$t('Delete') || 'Delete'"
      :cancel-text="$t('Cancel')"
      confirm-variant="danger"
      :loading="deleting"
      @confirm="performDelete"
    />

    <Modal v-model="modalOpen" :title="form.id ? ($t('EditItem') || 'Edit Item') : ($t('AddItem') || 'Add Item')" size="xl">
      <form class="bip-form" @submit.prevent="save">

        <!-- Reference numbers — internal one is auto-generated and read-only -->
        <div class="form-row">
          <div class="form-field">
            <label>{{ $t('ReferenceNumber') || 'Reference number' }}</label>
            <input
              :value="form.referenceNumber || ($t('AutoGenerated') || 'Auto-generated on save')"
              class="form-input is-readonly"
              disabled
            />
          </div>
          <div class="form-field">
            <label>{{ $t('ExternalReference') || 'External reference' }}</label>
            <input v-model="form.externalReferenceNumber" class="form-input" />
          </div>
        </div>

        <!-- Content (rich text) — REQUIRED -->
        <div class="form-field">
          <label>
            {{ $t('Content') || 'Content' }}
            <span class="bip-required">*</span>
          </label>
          <TextEditor
            v-model="form.content"
            :placeholder="$t('BidItemContentPlaceholder') || 'Describe the bid clause/item content'"
          />
        </div>

        <!-- Type (REQUIRED) + Due date (REQUIRED) -->
        <div class="form-row">
          <div class="form-field">
            <label>
              {{ $t('ItemType') || 'Item Type' }}
              <span class="bip-required">*</span>
            </label>
            <CustomSelect
              v-model="form.itemTypeId"
              :options="itemTypeOptions"
              value-key="id"
              label-key="name"
              :placeholder="$t('Select')"
            />
          </div>
          <div class="form-field">
            <label>
              {{ $t('DueDate') || 'Due date' }}
              <span class="bip-required">*</span>
            </label>
            <DatePicker v-model="form.dueDate" :placeholder="$t('SelectDate') || 'Select date'" />
          </div>
        </div>

        <!-- Tags — prominent, replaces the old Classification slot per user request -->
        <div class="form-field">
          <label>{{ $t('Tags') || 'Tags' }}</label>
          <TagPicker :model-value="form.tagIds || []" @update:model-value="(v) => (form.tagIds = v)" />
        </div>

        <!-- Related item (optional) + Order -->
        <div class="form-row">
          <div class="form-field">
            <label>{{ $t('RelatedItem') || 'Related Item' }}</label>
            <CustomSelect
              v-model="form.relatedItemId"
              :options="relatableItemOptions"
              value-key="id"
              label-key="name"
              :placeholder="$t('LinkToExistingItem') || 'Link to an existing committee item'"
              searchable
              clearable
            />
          </div>
          <div class="form-field">
            <label>{{ $t('Order') || 'Order' }}</label>
            <input v-model.number="form.order" type="number" class="form-input" min="0" />
          </div>
        </div>

        <div class="form-field">
          <label>{{ $t('InternalNote') || 'Internal note' }}</label>
          <input v-model="form.internalNote" class="form-input" />
        </div>

        <div class="form-actions">
          <button type="button" class="btn-secondary" @click="modalOpen = false">{{ $t('Cancel') }}</button>
          <button type="submit" class="btn-primary" :disabled="saving || !isFormValid">{{ $t('Save') }}</button>
        </div>
      </form>
    </Modal>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Icon from '@/components/ui/Icon.vue'
import Modal from '@/components/ui/Modal.vue'
import ConfirmModal from '@/components/ui/ConfirmModal.vue'
import DatePicker from '@/components/ui/DatePicker.vue'
import CustomSelect from '@/components/ui/CustomSelect.vue'
import TextEditor from '@/components/ui/TextEditor.vue'
import TagPicker from '@/components/ui/TagPicker.vue'
import BidsService, { type BidItem, type BidItemPost } from '@/services/BidsService'
import { useToast } from '@/composables/useToast'
import { useI18n } from 'vue-i18n'

interface Props { bidId: number; items: BidItem[]; canEdit: boolean }
const props = defineProps<Props>()
const emit = defineEmits<{ changed: [] }>()

const { t } = useI18n()
const { toast } = useToast()

const modalOpen = ref(false)
const saving = ref(false)
const form = ref<{ id?: number } & BidItemPost>(emptyForm())

// Lookup data for the item-type and related-item pickers.
// Classification (BidItemType §5.11) was removed from this form per user request —
// tags fill that slot. Procurement-specific classification will be set in the
// procurement UI (#30) where it actually applies.
const itemTypeOptions = ref<{ id: string; name: string }[]>([])
const relatableItemOptions = ref<{ id: string; name: string }[]>([])

function emptyForm(): BidItemPost {
  return {
    referenceNumber: '',
    externalReferenceNumber: null,
    content: '',
    internalNote: null,
    order: (props.items?.length || 0) + 1,
    dueDate: null,
    bidItemTypeId: null,
    itemTypeId: null,
    relatedItemId: null,
    tagIds: []
  }
}

/**
 * Live form validity — drives the Save button's disabled state instead of
 * showing red borders. Strips HTML tags so an "empty" TipTap doc (`<p></p>`)
 * is correctly treated as missing.
 */
const isFormValid = computed(() => {
  const stripped = (form.value.content || '').replace(/<[^>]+>/g, '').trim()
  return !!stripped && !!form.value.itemTypeId && !!form.value.dueDate
})

const sortedItems = computed(() => [...props.items].sort((a, b) => a.order - b.order || a.id - b.id))

function openAddModal() { form.value = emptyForm(); modalOpen.value = true }
function openEditModal(item: BidItem) {
  form.value = {
    id: item.id,
    referenceNumber: item.referenceNumber,
    externalReferenceNumber: item.externalReferenceNumber,
    content: item.content,
    internalNote: item.internalNote,
    order: item.order,
    dueDate: item.dueDate || null,
    bidItemTypeId: item.bidItemTypeId || null,
    itemTypeId: item.itemTypeId || null,
    relatedItemId: item.relatedItemId || null,
    tagIds: (item.tagList || []).map(t => Number(t.id)).filter(n => !isNaN(n))
  }
  modalOpen.value = true
}

async function loadLookups() {
  try {
    const [types, relatable]: any = await Promise.all([
      BidsService.listItemTypes().catch(() => []),
      BidsService.listRelatableItems(props.bidId).catch(() => [])
    ])
    itemTypeOptions.value = (types?.data ?? types ?? []).map((t: any) => ({ id: String(t.id), name: t.name }))
    relatableItemOptions.value = (relatable?.data ?? relatable ?? []).map((r: any) => ({ id: String(r.id), name: r.name }))
  } catch { /* fail-silent — pickers just show empty */ }
}

onMounted(loadLookups)

async function save() {
  if (!isFormValid.value) return
  saving.value = true
  try {
    const { id, ...payload } = form.value
    if (id) await BidsService.updateItem(id, payload)
    else await BidsService.addItem(props.bidId, payload)
    toast.success(t('Saved') || 'Saved')
    modalOpen.value = false
    emit('changed')
  } catch (err: any) {
    toast.error(err?.response?.data?.message || t('ErrorOccured'))
  } finally {
    saving.value = false
  }
}

function formatDate(iso: string) { return new Date(iso).toLocaleDateString() }
function isOverdue(iso: string): boolean { return new Date(iso).getTime() < Date.now() }

// Delete uses the styled ConfirmModal instead of native browser confirm()
const confirmOpen = ref(false)
const deleting = ref(false)
const pendingDelete = ref<BidItem | null>(null)

function confirmDelete(item: BidItem) {
  pendingDelete.value = item
  confirmOpen.value = true
}

async function performDelete() {
  if (!pendingDelete.value) return
  deleting.value = true
  try {
    await BidsService.deleteItem(pendingDelete.value.id)
    toast.success(t('Deleted') || 'Deleted')
    confirmOpen.value = false
    pendingDelete.value = null
    emit('changed')
  } catch (err: any) {
    toast.error(err?.response?.data?.message || t('ErrorOccured'))
  } finally {
    deleting.value = false
  }
}
</script>

<style scoped>
.bid-items-panel { display: flex; flex-direction: column; gap: 12px; }
.bip-head { display: flex; justify-content: space-between; align-items: center; }
.bip-head h3 {
  margin: 0; display: flex; align-items: center; gap: 6px;
  font-size: 14px; font-weight: 700; color: #1a2e25;
}
.bip-count {
  display: inline-flex; align-items: center; justify-content: center;
  min-width: 22px; height: 20px; padding: 0 7px;
  background: rgba(0, 109, 75, 0.1); color: #006d4b;
  border-radius: 10px; font-size: 11px; font-weight: 700;
}
.btn-primary, .btn-secondary {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 8px 14px; border-radius: 8px; font-size: 13px; font-weight: 600;
  cursor: pointer; font-family: inherit; transition: all 0.15s; border: 1px solid transparent;
}
.btn-primary { background: #006d4b; color: #fff; }
.btn-primary:hover:not(:disabled) { background: #005339; }
.btn-primary:disabled { opacity: 0.55; cursor: not-allowed; }
.btn-primary.btn-sm { padding: 6px 11px; font-size: 12px; }
.btn-secondary { background: #fff; color: #374a41; border-color: #d4e0da; }
.btn-secondary:hover { background: #f4f8f6; }

.bip-empty {
  display: flex; flex-direction: column; align-items: center;
  justify-content: center;
  gap: 10px; min-height: 200px; padding: 32px 20px;
  background: #f7faf8; border: 1px dashed #d4e0da; border-radius: 10px;
  color: #93afa4; font-size: 13px; text-align: center;
}
.bip-empty p { margin: 0; max-width: 480px; color: #6b8a7d; }

.bip-list { display: flex; flex-direction: column; gap: 10px; }
.bip-item {
  background: #f7faf8; border: 1px solid #e4ede8; border-radius: 10px;
  padding: 12px 14px; transition: all 0.15s;
}
.bip-item:hover { border-color: #c8ddd3; }
.bip-item-head { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; flex-wrap: wrap; }
.bip-ref {
  display: inline-flex; align-items: center; gap: 4px;
  padding: 3px 9px; border-radius: 8px;
  background: #e8f5ef; color: #006d4b;
  font-size: 11px; font-weight: 700;
}
.bip-ref-ext { font-size: 11px; color: #6b8a7d; padding: 2px 7px; background: #fff; border-radius: 6px; border: 1px solid #d4e0da; }
.bip-order { font-size: 10px; font-weight: 700; color: #6b8a7d; padding: 1px 6px; background: #fff; border-radius: 6px; border: 1px solid #d4e0da; }
.bip-item-actions { margin-inline-start: auto; display: flex; gap: 4px; }
.bip-content { font-size: 13px; color: #1a2e25; line-height: 1.55; white-space: pre-line; }
.bip-item-meta { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px; }
.bip-due {
  display: inline-flex; align-items: center; gap: 4px; padding: 3px 9px;
  background: #fff; border: 1px solid #d4e0da; border-radius: 6px;
  color: #6b8a7d; font-size: 11px; font-weight: 600;
}
.bip-due.overdue { background: #fef2f2; border-color: #fca5a5; color: #b91c1c; }
.bip-overdue { font-style: normal; padding: 1px 6px; background: #fee2e2; color: #b91c1c; border-radius: 6px; font-size: 10px; font-weight: 700; margin-inline-start: 3px; }
.bip-note { display: inline-flex; align-items: center; gap: 5px; padding: 3px 9px; background: #fff7ed; border: 1px solid #fed7aa; border-radius: 6px; color: #9a3412; font-size: 11px; font-weight: 500; }

.icon-btn {
  background: transparent; border: 1px solid #e4ede8; border-radius: 6px;
  padding: 4px 6px; cursor: pointer; color: #475569; transition: all 0.15s;
}
.icon-btn:hover { background: #fff; color: #006d4b; }
.icon-btn-danger:hover { background: #fef2f2; color: #b91c1c; border-color: #fca5a5; }

/* Modal form */
.bip-form { display: flex; flex-direction: column; gap: 12px; }
.form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.form-field { display: flex; flex-direction: column; gap: 4px; }
.form-field label { font-size: 12px; font-weight: 600; color: #374a41; }
.form-input {
  padding: 10px 12px; border: 1.5px solid #d4e0da; border-radius: 8px;
  font-size: 14px; background: #f7faf8; color: #1a2e25; font-family: inherit;
}
.form-input:focus { outline: none; border-color: #006d4b; background: #fff; box-shadow: 0 0 0 3px rgba(0, 109, 75, 0.1); }
.form-input.is-readonly {
  background: #f1f5f9; color: #6b8a7d; cursor: not-allowed;
  font-style: italic;
}
.form-actions { display: flex; justify-content: flex-end; gap: 8px; padding-top: 8px; border-top: 1px solid #e4ede8; margin-top: 6px; }

/* Required-field asterisk — no red borders; the disabled Save button signals invalid state */
.bip-required { color: #b91c1c; font-weight: 700; margin-inline-start: 2px; }

@media (max-width: 768px) { .form-row { grid-template-columns: 1fr; } }
</style>
