<template>
  <div class="meeting-form">
    <!-- Row 1: Subject (Full Width) -->
    <div class="form-row">
      <div class="form-group col-span-full">
        <label class="form-label">
          {{ $t('Subject') }}
          <span class="required">*</span>
          <span v-if="errors.title" class="label-error">{{ errors.title }}</span>
        </label>
        <textarea
          v-model="localMeeting.title"
          rows="2"
          class="form-input"
          :class="{ 'error': errors.title }"
          :placeholder="$t('EnterMeetingSubject')"
          :disabled="viewMode"
        ></textarea>
      </div>
    </div>

    <!-- Row 2: Related Committee & Reference -->
    <div class="form-row" :class="localMeeting.isCommittee ? 'grid-cols-3' : (hasCommitteePermission ? 'grid-cols-2' : 'grid-cols-1')">
      <!-- Only show toggle if user has permission to create committee meetings -->
      <div class="form-group" v-if="hasCommitteePermission">
        <label class="form-label">
          {{ $t('RelatedCommittee') }}
        </label>
        <div class="toggle-group">
          <button
            type="button"
            :class="['toggle-btn', !localMeeting.isCommittee ? 'active' : '']"
            :disabled="viewMode"
            @click="setCommittee(false)"
          >
            {{ $t('PersonalMeeting') }}
          </button>
          <button
            type="button"
            :class="['toggle-btn', localMeeting.isCommittee ? 'active' : '']"
            :disabled="viewMode"
            @click="setCommittee(true)"
          >
            {{ $t('CommitteeMeeting') }}
          </button>
        </div>
      </div>

      <div class="form-group" v-if="localMeeting.isCommittee">
        <label class="form-label">
          {{ $t('Committee') }}
          <span class="required">*</span>
        </label>
        <Combobox
          v-model="localMeeting.committeeId"
          :options="committees"
          item-value="id"
          item-text="label"
          :placeholder="$t('SelectCommittee')"
          :disabled="viewMode"
          @update:model-value="onCommitteeChange"
        />
      </div>

      <div class="form-group">
        <label class="form-label">
          {{ $t('ReferenceNumber') }}
        </label>
        <Input
          v-model="localMeeting.referenceNumber"
          disabled
          :placeholder="$t('AutoGenerated')"
        />
      </div>
    </div>

    <!-- Row 2b: Council Session (if committee meeting and has session) -->
    <div class="form-row grid-cols-2" v-if="localMeeting.isCommittee && showCouncilSession">
      <div class="form-group">
        <CustomSelect
          v-model="localMeeting.councilSessionId"
          :options="councilSessions"
          :label="$t('CouncilSession')"
          :placeholder="$t('SelectSession')"
          value-key="id"
          label-key="name"
          :disabled="viewMode"
          clearable
        />
      </div>
    </div>

    <!-- Row 3: Date & Time -->
    <div class="form-row grid-cols-3">
      <div class="form-group">
        <label class="form-label">
          {{ $t('MeetingDate') }}
          <span class="required">*</span>
          <span v-if="errors.date" class="label-error">{{ errors.date }}</span>
        </label>
        <DatePicker
          v-model="localMeeting.date"
          :placeholder="$t('SelectDate')"
          :disabled="viewMode"
        />
      </div>

      <div class="form-group">
        <label class="form-label">
          {{ $t('StartTime') }}
          <span class="required">*</span>
        </label>
        <TimePicker
          v-model="localMeeting.startTime"
          :placeholder="$t('SelectTime')"
          :disabled="viewMode"
        />
      </div>

      <div class="form-group">
        <label class="form-label">
          {{ $t('EndTime') }}
          <span v-if="errors.endTime" class="label-error">{{ errors.endTime }}</span>
        </label>
        <TimePicker
          v-model="localMeeting.endTime"
          :placeholder="$t('SelectTime')"
          :disabled="viewMode"
        />
      </div>
    </div>

    <!-- Row 4: Location & Meeting Type -->
    <div class="form-row grid-cols-2">
      <div class="form-group">
        <label class="form-label">
          {{ $t('Location') }}
          <span class="required">*</span>
          <span v-if="errors.location" class="label-error">{{ errors.location }}</span>
        </label>
        <Input
          v-model="localMeeting.location"
          :placeholder="$t('EnterLocation')"
          :disabled="viewMode"
        />
      </div>

      <div class="form-group">
        <CustomSelect
          v-model="localMeeting.typeId"
          :options="meetingTypes.filter(t => t)"
          :label="$t('MeetingType')"
          :placeholder="$t('SelectMeetingType')"
          value-key="id"
          label-key="name"
          :disabled="viewMode"
          :error="errors.typeId"
        />
      </div>
    </div>

    <!-- Row 5: Meeting URL (for remote meetings) -->
    <div class="form-row" v-if="isRemoteMeeting">
      <div class="form-group col-span-full">
        <label class="form-label">
          {{ $t('MeetingUrl') }}
          <span class="required">*</span>
          <span v-if="errors.url" class="label-error">{{ errors.url }}</span>
        </label>
        <Input
          v-model="localMeeting.url"
          type="url"
          :placeholder="$t('EnterMeetingUrl')"
          :disabled="viewMode"
        />
      </div>
    </div>

    <!-- Row 6: Notes -->
    <div class="form-row">
      <div class="form-group col-span-full">
        <label class="form-label">
          {{ $t('Notes') }}
          <span class="optional">({{ $t('Optional') }})</span>
        </label>
        <textarea
          v-model="localMeeting.notes"
          rows="3"
          class="form-input"
          :placeholder="$t('EnterNotesPlaceholder')"
          :disabled="viewMode"
        ></textarea>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import Input from '@/components/ui/Input.vue'
import Combobox from '@/components/ui/Combobox.vue'
import CustomSelect from '@/components/ui/CustomSelect.vue'
import DatePicker from '@/components/ui/DatePicker.vue'
import TimePicker from '@/components/ui/TimePicker.vue'
import CouncilCommitteesService from '@/services/CouncilCommitteesService'
import LookupsService from '@/services/LookupsService'

const { t } = useI18n()

export interface MeetingData {
  id?: number
  title: string | null
  isCommittee: boolean
  committeeId: string | null
  committeeName?: string | null
  committeeTypeId?: string | null
  date: string | null
  startTime: string
  endTime: string
  location: string | null
  notes: string | null
  typeId: string | null
  url: string | null
  councilSessionId: string | null
  referenceNumber: string | null
}

interface Props {
  modelValue: MeetingData
  viewMode?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  viewMode: false
})

const emit = defineEmits<{
  'update:modelValue': [value: MeetingData]
}>()

// Local state
const localMeeting = ref<MeetingData>({ ...props.modelValue })
const committees = ref<Array<{ id: string; name: string; label: string; typeId?: string }>>([])
const councilSessions = ref<Array<{ id: string; name: string }>>([])
const meetingTypes = ref<Array<{ id: string; name: string; code?: string }>>([])
const errors = ref<Record<string, string>>({})

// Flag to prevent infinite loop between watchers
let isUpdatingFromProps = false

// Computed
// Check if user has permission to create meetings for any committee/council
const hasCommitteePermission = computed(() => {
  return committees.value.length > 0
})

const showCouncilSession = computed(() => {
  // Show council session for specific committee types
  const selectedCommittee = committees.value.find(c => c.id === localMeeting.value.committeeId)
  return selectedCommittee?.typeId === 'council' // Adjust based on actual type
})

// Helper to check if a type is remote
const isTypeRemote = (type: { id: string; name: string; code?: string } | null | undefined): boolean => {
  if (!type) return false
  return type.code === 'remote' || type.name?.toLowerCase().includes('عن بعد') || type.name?.toLowerCase().includes('remote')
}

const isRemoteMeeting = computed(() => {
  const selectedType = meetingTypes.value.find(t => String(t.id) === String(localMeeting.value.typeId))
  return isTypeRemote(selectedType)
})

// Watch for external changes
watch(() => props.modelValue, (newVal) => {
  if (JSON.stringify(newVal) !== JSON.stringify(localMeeting.value)) {
    isUpdatingFromProps = true
    localMeeting.value = { ...newVal }
    nextTick(() => {
      isUpdatingFromProps = false
    })
  }
}, { deep: true })

// Watch for local changes and emit
watch(localMeeting, (newVal) => {
  if (!isUpdatingFromProps) {
    emit('update:modelValue', { ...newVal })
  }
}, { deep: true, flush: 'sync' })

// Watch start/end time for real-time validation
watch(
  () => [localMeeting.value.startTime, localMeeting.value.endTime],
  ([startTime, endTime]) => {
    if (startTime && endTime) {
      const start = startTime.split(':').map(Number)
      const end = endTime.split(':').map(Number)
      const startMinutes = start[0] * 60 + start[1]
      const endMinutes = end[0] * 60 + end[1]
      if (endMinutes <= startMinutes) {
        errors.value.endTime = t('EndTimeMustBeAfterStart')
      } else {
        delete errors.value.endTime
      }
    }
  }
)

// Methods
const setCommittee = (value: boolean) => {
  localMeeting.value.isCommittee = value
  if (!value) {
    localMeeting.value.committeeId = null
    localMeeting.value.councilSessionId = null
  }
}

const onCommitteeChange = (committeeId: string) => {
  const committee = committees.value.find(c => c.id === committeeId)
  if (committee) {
    localMeeting.value.committeeName = committee.name
    localMeeting.value.committeeTypeId = committee.typeId
  }
}

const loadCommittees = async () => {
  try {
    const response = await CouncilCommitteesService.listUserCommitteesForMeeting()
    const data = Array.isArray(response) ? response : (response?.data || [])
    committees.value = data.map((c: any) => ({
      id: c.id,
      name: c.name,
      label: c.name,
      typeId: c.typeId
    }))

    // If no committees available (no permission), ensure personal meeting mode
    if (committees.value.length === 0 && localMeeting.value.isCommittee) {
      localMeeting.value.isCommittee = false
      localMeeting.value.committeeId = null
      localMeeting.value.councilSessionId = null
    }
  } catch (error) {
    console.error('Failed to load committees:', error)
    // On error, ensure personal meeting mode as fallback
    if (localMeeting.value.isCommittee) {
      localMeeting.value.isCommittee = false
      localMeeting.value.committeeId = null
    }
  }
}

const loadMeetingTypes = async () => {
  try {
    const response = await LookupsService.getMeetingTypes()
    const data = Array.isArray(response) ? response : (response?.data || [])
    meetingTypes.value = data.filter((t: any) => t && t.id)
  } catch (error) {
    console.error('Failed to load meeting types:', error)
  }
}

const loadCouncilSessions = async () => {
  try {
    const response = await LookupsService.getCouncilSessions()
    councilSessions.value = response || []
  } catch (error) {
    console.error('Failed to load council sessions:', error)
  }
}

// Validation
const validate = (): boolean => {
  errors.value = {}

  if (!localMeeting.value.title?.trim()) {
    errors.value.title = t('SubjectRequired')
  }

  if (!localMeeting.value.location?.trim()) {
    errors.value.location = t('LocationRequired')
  }

  if (!localMeeting.value.date) {
    errors.value.date = t('DateRequired')
  }

  if (!localMeeting.value.typeId) {
    errors.value.typeId = t('MeetingTypeRequired')
  }

  if (isRemoteMeeting.value && !localMeeting.value.url?.trim()) {
    errors.value.url = t('MeetingUrlRequired')
  }

  // Validate end time is after start time
  if (localMeeting.value.startTime && localMeeting.value.endTime) {
    const start = localMeeting.value.startTime.split(':').map(Number)
    const end = localMeeting.value.endTime.split(':').map(Number)
    const startMinutes = start[0] * 60 + start[1]
    const endMinutes = end[0] * 60 + end[1]
    if (endMinutes <= startMinutes) {
      errors.value.endTime = t('EndTimeMustBeAfterStart')
    }
  }

  return Object.keys(errors.value).length === 0
}

// Expose validate method
defineExpose({ validate })

// Lifecycle
onMounted(() => {
  loadCommittees()
  loadMeetingTypes()
  loadCouncilSessions()
})
</script>

<style scoped>
.meeting-form {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

/* Form layout */
.form-row {
  display: grid;
  gap: 1.25rem;
  grid-template-columns: 1fr;
}

@media (min-width: 768px) {
  .form-row {
    grid-template-columns: repeat(2, 1fr);
  }

  .form-row.grid-cols-3 {
    grid-template-columns: repeat(3, 1fr);
  }

  .form-row.grid-cols-4 {
    grid-template-columns: repeat(4, 1fr);
  }
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

/* Align CustomSelect label with form-label spacing */
.form-row :deep(.select-label) {
  margin-bottom: 13px !important;
}

.form-group.col-span-full {
  grid-column: 1 / -1;
}

.form-group.col-span-2 {
  grid-column: span 2;
}

/* Labels */
.form-label {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: #3f3f46;
  flex-wrap: wrap;
}

.required {
  color: #ef4444;
}

.optional {
  color: #a1a1aa;
  font-weight: 400;
  font-size: 0.75rem;
}

.label-error {
  color: #ef4444;
  font-weight: 400;
  font-size: 0.75rem;
  margin-inline-start: auto;
}

/* Unified input styles */
.form-input {
  width: 100%;
  height: 44px;
  padding: 0 1rem;
  font-size: 0.875rem;
  color: #18181b;
  background-color: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 0.5rem;
  transition: all 0.15s ease;
}

.form-input:hover:not(:disabled) {
  border-color: #d4d4d8;
}

.form-input:focus {
  outline: none;
  border-color: var(--color-primary, #006d4b);
  box-shadow: 0 0 0 3px rgba(0, 109, 75, 0.1);
}

.form-input:disabled {
  background-color: #fafafa;
  color: #71717a;
  cursor: not-allowed;
}

.form-input.error {
  border-color: #ef4444;
}

.form-input.error:focus {
  box-shadow: 0 0 0 3px rgba(239, 68, 68, 0.1);
}

/* Textarea specific */
textarea.form-input {
  height: auto;
  min-height: 80px;
  padding: 0.75rem 1rem;
  resize: none;
}

/* Select specific */
select.form-input {
  appearance: none;
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
  background-position: left 0.75rem center;
  background-repeat: no-repeat;
  background-size: 1.25rem;
  padding-left: 2.5rem;
}

[dir="ltr"] select.form-input {
  background-position: right 0.75rem center;
  padding-left: 1rem;
  padding-right: 2.5rem;
}

/* Toggle group */
.toggle-group {
  display: flex;
  height: 44px;
  border-radius: 0.5rem;
  overflow: hidden;
  border: 1px solid #e4e4e7;
  background-color: #fff;
}

.toggle-btn {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 1rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: #71717a;
  background: transparent;
  border: none;
  cursor: pointer;
  transition: all 0.15s ease;
}

.toggle-btn:hover:not(:disabled):not(.active) {
  background-color: #fafafa;
  color: #3f3f46;
}

.toggle-btn.active {
  background-color: var(--color-primary, #006d4b);
  color: white;
}

.toggle-btn:disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

/* Error & hints */
.form-error {
  font-size: 0.75rem;
  color: #ef4444;
  margin-top: 0.25rem;
}

.form-hint {
  font-size: 0.75rem;
  color: #71717a;
  margin-top: 0.25rem;
}

/* Responsive adjustments */
@media (max-width: 640px) {
  .form-row.grid-cols-3,
  .form-row.grid-cols-4 {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 480px) {
  .form-row.grid-cols-2,
  .form-row.grid-cols-3,
  .form-row.grid-cols-4 {
    grid-template-columns: 1fr;
  }
}
</style>
